set( LLVM_BIN ${CMAKE_SOURCE_DIR}/llvm/src/LLVM-build/bin )
set( CLANG_BIN ${CMAKE_SOURCE_DIR}/llvm/tools/clang/src/CLANG-build/bin )

function( BUILD_BYTECODE_AR FLAGS FILES DESTINATION TEMP_DIR )
  message( "in function BUILD_BYTECODE_AR:" )
  message( "FLAGS is ${FLAGS}" )
  message( "FILES is ${FILES}" )
  message( "DESTINATION is ${DESTINATION}" )
  message( "TEMP_DIR is ${TEMP_DIR}" )
  foreach( SF ${FILES} )
    execute_process( COMMAND "${CLANG_BIN}/clang++ ${FLAGS} -o ${TEMP_DIR}/${SF}.ll -S -emit-llvm" )
    execute_process( COMMAND "${LLVM_BIN}/llvm-as ${TEMP_DIR}/${SF}.ll -o - | ${LLVM_BIN}/opt -std-compile-opts -o ${SF}.bc" )
  endforeach( SF )
  file( GLOB BC_FILES ${TEMP_DIR}/*.bc )
  execute_process( COMMAND " ${LLVM_BIN}/llvm-ar rcsf ${DESTINATION} ${BC_FILES}" )
endfunction( BUILD_BYTECODE_AR )